<?php
/**
 * User: matt
 * Date: 23/06/14
 * Time: 10:12
 */


/**
 * Class EHBuilder
 *
 * Runs command line arguments generated by EHServerBuilder and EHDriveBuilder
 *
 */

class EHBuilder {


    private $serverBuilder;
    private $driveBuilder;


    public function __construct (EHServerBuilder $serverBuilder, EHDriveBuilder $driveBuilder) {
        $this->serverBuilder = $serverBuilder;
        $this->driveBuilder = $driveBuilder;
    }

    public function build (EHServer $server) {

    }
} 